# Generated by Django 5.0 on 2024-01-12 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanakarn', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_code',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
