# Generated by Django 5.0 on 2024-01-12 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanakarn', '0002_customer_customer_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='balance',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
