# Generated by Django 5.0 on 2024-01-13 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanakarn', '0003_alter_customer_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[('ฝาก', 'Withdraw'), ('ถอน', 'Deposit')]),
        ),
    ]
