# Generated by Django 5.0 on 2024-01-13 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tanakarn', '0004_alter_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.IntegerField(choices=[(1, 'Withdraw'), (-1, 'Deposit')]),
        ),
    ]
