# Generated by Django 5.0 on 2024-01-17 03:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tanakarn', '0005_alter_transaction_type'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='phone_number',
            new_name='id_card',
        ),
    ]
